USE [master]
GO

/****** Object:  Database [KhanaMangwanaDatabase]    Script Date: 05-Dec-2018 12:34:08 PM ******/
CREATE DATABASE [KhanaMangwanaDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KhanaMangwanaDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\KhanaMangwanaDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'KhanaMangwanaDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\KhanaMangwanaDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KhanaMangwanaDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [KhanaMangwanaDatabase] SET  READ_WRITE 
GO


